### ISSUE TITLE
Not a bug

### ISSUE THREAD

**Issue by stevenbaert** [letta-ai/letta#1461]
Hi,

To clarify: not a bug, just a general question. Feel free to delete afterwards /point me to correct destination for such questions.

I've been following your project for quite some time now and really love what you're doing. However, I've never fully committed to using it due to some issues with speed and a lack of certain features.

My question is: has the project reached a level of maturity and speed that would allow it to be used as a daily driver for myself and my colleagues at work? Ideally, I'm looking for response times and functionalities similar to GPT-4, possibly using Groq, with voice capabilities, a web interface, and, of course, extensive memory.

Is this something that's feasible?

Thanks!

**Comment by sarahwooders** [comment]
Thanks for following the project! We have support for a lot of the things you mentioned (or will soon): 

- We added support for Groq recently, but it hasn't been extensively tested so may have issues. 
- We are working on integrating with Vapi by supporting streaming chat competitions https://github.com/cpacker/MemGPT/pull/1280
- We have a web interface coupled with the server -- you can see the instructions for setting up the dev portal UI in the README (probably with docker is the easiest)

To be completely honest, we are still in the process of improving stability and fixing bugs, so you may face issues with trying these things, so might want to wait a few weeks if you want think to just work. But if you try things sooner, we can also try to prioritize the bugs/features that are important to your use case :)

**Comment by stevenbaert** [comment]
> Thanks for following the project! We have support for a lot of the things you mentioned (or will soon): 
> 
> - We added support for Groq recently, but it hasn't been extensively tested so may have issues. 
> - We are working on integrating with Vapi by supporting streaming chat competitions https://github.com/cpacker/MemGPT/pull/1280
> - We have a web interface coupled with the server -- you can see the instructions for setting up the dev portal UI in the README (probably with docker is the easiest)
> 
> To be completely honest, we are still in the process of improving stability and fixing bugs, so you may face issues with trying these things, so might want to wait a few weeks if you want think to just work. But if you try things sooner, we can also try to prioritize the bugs/features that are important to your use case :) 


Thanks for your feedback, but it surprises me. This project is there for more than a year, right? So still no stable version then?

**Comment by cpacker** [comment]
> Thanks for your feedback, but it surprises me. This project is there for more than a year, right? So still no stable version then?

The project was originally released in October (so ~8 months ago), but it's evolved a lot over time: initially it was mainly a CLI tool to experiment with the concept of self-editing memory + LLMs (an implementation of an LLM OS as described in the [MemGPT research paper](https://research.memgpt.ai/)), then at the beginning of this year we began expanding the repo to support building LLM applications on top of a MemGPT-backed REST API (so going from a CLI tool to a service). This redesign has taken a few months since the core contributors were finishing their PhDs at the same time, but now that the PhDs are done you can expect the pace of development to significantly increase - we're targeting a stable production build on the server ready this summer. If you have any particular feature requests please let us know, we're happy to adjust the immediate roadmap based on user feedback. And thanks so much for following the project!

**Comment by stevenbaert** [comment]
Would appreciate a status update a lot in order to understand current situation. Thanks!
