### ISSUE TITLE
standardize inner thoughts terminology

### ISSUE THREAD

**Issue by kl2806** [letta-ai/letta#1918]
Currently, there are several terms that refer to the same concept in the repo:
- inner thoughts
- inner monologue
- internal monologue
To avoid confusion, these should be standardized to a single name eg. "inner thoughts," and we should only have different terminology if we add additional conceptual differences i.e. thoughts that are only visible to a single agent in a mult-agent system.

**Comment by raolak** [comment]
The current stream response should have more well defined spec . Also leverage [opeai](https://openai.com/index/introducing-structured-outputs-in-the-api/) feature so that clients can building much more flexible rendering capabilities .

Example
Based on type of response (md, csv, chart, code, image, diff, data payloads etc ), one should able to design rendering plugin components... even its possible the executable plugins can be part of stream response. The UI execution sandbox within the browser can safely execute those executable plugins
