### ISSUE TITLE
Add LLM Model list to the Settings Menu

### ISSUE THREAD

**Issue by syndicate604** [letta-ai/letta#2017]
**Is your feature request related to a problem? Please describe.*
Anthropic models are hard-coded and buried in a source file.  Right now the latest models are not listed (big drop in performance). Also Haiku has two versions at different prices.  Massive loss of performance/cost at the moment.  

**Describe the solution you'd like**
Add a way to edit the Anthropic and other LLM models from the Dashboard or Settings or an easy to access config file

**Describe alternatives you've considered**
Update the docs with the exact location and how to updated the models

**Comment by sarahwooders** [comment]
Yes we can add instructions for adding additional models. Unfortunately we had to hard-code it since Anthropic doesn't provide a model listing endpoint that includes context window information, unlike other APIs. 

You can actually specify the model even if it's not listed by just setting `model_name`: 
```python
from letta import create_client, LLMConfig

client = create_client()

# provide full config (llm config)
client.set_default_llm_config(
    LLMConfig(
        model="claude-3-5-haiku-latest",
        model_endpoint_type="anthropic",
        model_endpoint="https://api.anthropic.com/v1",
        context_window=200000 # NOTE: can be set to <= 200000
    )
)
```
