### ISSUE TITLE
Got imports error when executing a tool

### ISSUE THREAD

**Issue by lemorage** [letta-ai/letta#2108]
**Describe the bug**
I followed the simple example in the letta tutorial, to create a tool and add the tool to an agent. I sent a specific message to the agent to make it execute the tool, however I constantly got `NameError: name 'Dict' is not defined` when the agent called the function, even though I already imported it from `typing`. My tool is written as follows:
```py
from typing import Dict, Union

async def get_weather_forecast_by_location(self: "Agent", location: str) -> Dict[str, Union[str, float]]:
    """
    Get the current weather for a given location.

    Args:
        location (str): The name of the location for which to retrieve weather information.

    Returns:
        dict: A dictionary containing weather data, including local time, temperature,
        wind speed, wind direction, weather description, and whether it's day or night.

    Example:
        >>> get_weather_forecast_by_location("Paris")
        {
            "location": "Paris",
            "time": "2024-11-25 18:45:00",
            "temperature": 15.0,
            "windspeed": 8.5,
            "winddirection": 332,
            "weather_description": "Clear",
            "is_day": 0,
        }
    """
    # remaining code......
   ```

**Please describe your setup**
- [X] How did you install letta?
  - `pip install letta`
- [X] Describe your setup
  - What's your OS (Windows/MacOS/Linux)? MacOS
  - How are you running `letta`? (`cmd.exe`/Powershell/Anaconda Shell/Terminal) Terminal

**Screenshots**

**Additional context**

**Letta Config**
Please attach your `~/.letta/config` file or copy past it below.
```
[defaults]
preset = memgpt_chat
persona = sam_pov
human = basic

[archival_storage]
type = chroma
path = /Users/clannad/.letta/chroma

[recall_storage]
type = sqlite
path = /Users/clannad/.letta

[metadata_storage]
type = sqlite
path = /Users/clannad/.letta

[version]
letta_version = 0.5.5
```
---

If you're not using OpenAI, please provide additional information on your local LLM setup:
N/A

**Comment by mattzh72** [comment]
Hi! Sorry a lot of changes have been made recently to the Tools in Letta - 

1. You don't have to include `self` in the function.
2. We don't have a great way yet of including the defined imports in the file as part of the Tool execution - for now, would you be able to return a stringified version of the dictionary? It should be fine, since it gets turned into string tokens to be passed into the LLM anyway.

**Comment by lemorage** [comment]
Got it! Thanks for the answer. Btw, I wonder if I marked the tool function as `async`, could the agents execute it properly?

**Comment by lemorage** [comment]
I am using an external API service, which recommends using `async/await` at all times. but anyways, if I could not use `async/await` in tool calling, maybe I can try to switch to sync approach to see what happens. Thank u!

**Comment by cpacker** [comment]
FYI @lemorage async won't work:
<img width="1172" alt="image" src="https://github.com/user-attachments/assets/2d06b8af-70d5-4f95-b029-48c2e631cbbb">

But if you make your function sync, it seems to work:
<img width="1188" alt="image" src="https://github.com/user-attachments/assets/8c18c4e7-ea5c-463b-9b35-1b8e9361bb8a">

^ This is using the new tool debugging (in create tool) in the new ADE (app.letta.com)

As a side-note, I'd generally recommend formatting the output to be a string within your tool, because if you don't, Letta (the runtime) will cast it down using Python's `str(...)`, which is probably not as pretty-printed as you would like if you're optimizing for LLM inputs.

I'm going to close this issue for now but if you realize that not being able to use `async` in your tool definitions is a serious blocker, I can re-open this issue and we can take another look!
