### ISSUE TITLE
Upgrade to ver. 6.0.2 crashed the product.

### ISSUE THREAD

**Issue by farzbood** [letta-ai/letta#2211]
**Describe the bug**
Hi everyone,
Upgrading from `letta (6.0.1)` to the` letta (6.0.2)` caused crash in both **Client** and **Server** `letta run` command.
`6.0.1` works properly. (in my both envs. described bellow)
Keep up with outstanding work ☮️ ✌️ 

**Please describe your setup**
- [ ] How did you install letta?
  - `pip install letta`? `pip install letta-nightly`? `git clone`?
I've two separate environments:
1) `pip install letta` (`CPython 3.11.2 - pyenv + venv`)
2) `uv add letta` (clean install & upgrade both fails for `6.0.2`) (`CPython 3.11.10 - uv managed`)
**P.S.**
`Poetry` installation from `git clone`, failed due to a yanked package! (for `6.01` , `6.0.2` not tried)
- [ ] Describe your setup
  - What's your OS (Windows/MacOS/Linux)?
  - **Win 10 x86_64**
  - How are you running `letta`? (`cmd.exe`/Powershell/Anaconda Shell/Terminal)
  - `cmd.exe`

**Screenshots**
![image](https://github.com/user-attachments/assets/01c83ee1-4a9b-4636-acd3-68a0660e2744)
![image](https://github.com/user-attachments/assets/7a61bfd5-49d3-4d54-a6da-1e06855defe2)
**Additional context**

**Letta Config**
Please attach your `~/.letta/config` file or copy past it below.
Default (no custom config.)
---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run Letta with local LLMs, please provide the following information:

- [ ] The exact model you're trying to use (e.g. `dolphin-2.1-mistral-7b.Q6_K.gguf`)
- [ ] The local LLM backend you are using (web UI? LM Studio?)
- [ ] Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)

**Comment by cpacker** [comment]
Hi @farzbood - we don't officially support database migrations between versions using `sqlite`. However, if you're using `postgres`, we actively maintain migration scripts so that you can carry over your agent data between versions.

The easiest way to use Letta with `postgres` is to use it via Docker:
```sh
# replace `~/.letta/.persist/pgdata` with wherever you want to store your data
docker run \
  -v ~/.letta/.persist/pgdata:/var/lib/postgresql/data \
  -p 8283:8283 \
  -e OPENAI_API_KEY="your_api_key" \
  letta/letta

# using a .env file instead of passing environment variables
docker run \
  -v ~/.letta/.persist/pgdata:/var/lib/postgresql/data \
  -p 8283:8283 \
  --env-file .env \
  letta/letta
```

In those above commands, your database files will get stored on your computer at `~/.letta/.persist/pgdata`, and because you're using `postgres`, every time you update your Letta version and run the container, it will also run an `alembic` script to migrate your database for you.

Sorry for any confusion here! If you have important data that you need to carry over / migrate to `postgres` feel free to reach out on Discord and we can try and help you move it.

**Comment by farzbood** [comment]
Well, I've no restrictions regarding **data-backend** to use, but **tight coupling** caused by attaching all `letta installations` **setup** to a **centralized location in User Profile folder of OS** (%USERPROFILE%/.letta/) is **restricting/conflicting** for scenarios like **A/B testing** that needs to have more than one` letta installation` (same and/or different versions) with **isolated setups/configurations** in parallel. (as I mentioned, I've more than one installations in isolated envs.)
How can we achieve that?
