### ISSUE TITLE
Add together.ai endpoint support

### ISSUE THREAD

**Issue by sarahwooders** [letta-ai/letta#570]
Should be very similar to vLLM support - https://docs.together.ai/docs/inference-rest

**Comment by cpacker** [comment]
IMO it's unclear if this should be put inside of `local_llm` or `openai_tools.py`:

- `openai_tools.py`:
  - This is where all the "paid hosted" endpoints are currently configured
  - afaik together.ai has no self-host option, so it fits better with openai + azure
  - you need a together API KEY, so it naturally is just another credential in a credentials file
- `local_llm`:
  - together is not openai compatible, and the custom REST integrations we already (eg vLLM) have look similar to what we'd add for together's `/inference` endpoint

**Comment by sarahwooders** [comment]
I think the `local_llm` approach you have in #596 makes more sense given it's not OpenAI compatible (is there some other REST API standard...?)

**Comment by gururise** [comment]
I am pretty sure together REST api is openai compatible. I'm currently using it on huggingface chat-ui.

**Comment by cpacker** [comment]
> I am pretty sure together REST api is openai compatible. I'm currently using it on huggingface chat-ui.

It needs to be OAI REST compatible with function calling support. Last time I checked a few weeks ago not all their models had function calling support + the performance was worse than using raw completions + our own function calling via prompt formatting / return parsing (this may have changed since). However it's probably worth supporting both (we technically already support OAI-compatible together API once #619 is merged and can be toggled on for together / or on by default).

**Comment by mattzh72** [comment]
https://github.com/letta-ai/letta/pull/2045
