### ISSUE TITLE
Read/Write to Obsidian.md Databases

### ISSUE THREAD

**Issue by JPyke3** [letta-ai/letta#602]
**Is your feature request related to a problem? Please describe.**
MemGPT is unable to directly interact with an [Obsidian.md](https://obsidian.md) Database. Obsidian is quite often used as a note taking tool and tends to be a massive storage for people's personal ideas, notes, documents, etc. Currently, you can just add an Obsidian DB to MemGPT by loading the Directory (It's literally just a folder with a bunch of `.md` files in it.), however, this just adds all the content to Archival Memory and doesn't allow the AI to write back.

**Describe the solution you'd like**
A method in which MemGPT can write back to obsidian as well as dynamically read from the obsidian vault.

**Describe alternatives you've considered**
N/a

**Additional context**
N/a

**Comment by nickknyc** [comment]
super interested in this - what I have been hoping to accomplish with various RAG approaches - having a virtually endless conversation has been a stumbling block - would be happy to participate in building requirements and testing form an end user perspective. I'm not going to much help on the coding side.

**Comment by AashishKumar-3002** [comment]
Hello @cpacker and @JPyke3,

I've been looking into the issue regarding the interaction between MemGPT and the Obsidian.md Database and I'm interested in contributing to its resolution. If this issue is still open, I would like to take it up.

Before I begin, I would like to understand a few details to ensure that my contributions align with your expectations:

1. Could you clarify the specific interactions that are desired between MemGPT and Obsidian? For instance, is the expectation for MemGPT to create new notes, or just modify existing ones?
2. How should conflicts be managed? Specifically, what should happen if a note is modified by both the user and MemGPT simultaneously?
3. @JPyke3, could you share any specific use cases you have in mind for this feature?
4. What kind of interface or commands are envisioned to control MemGPT’s interactions with Obsidian?
5. How should errors or issues be reported to the user?

Your insights on these points would be greatly appreciated and would help me contribute effectively to this issue.

**Comment by nickknyc** [comment]
from my perspective a few things

in talking about obsidian - better to say vault rather than database. it is simply a large collection of markdown files.

i feel it is essential that the solution be able to keep the users entire vault in memory - the idea behind obsidian is that it is your "second brain"

obsidian has a number of ways of adding metadata to every. md file. I feel that this is a critical capability to exploit - creating metadata that is both human readable and, if helpful, metadata that is tool/llm specific.

more on metadata - i am very interested in having some knowledge graph capability here as well. I am after a system that will allow the user to create/edit a personal knowledge graph that will allow the user to provide explicit guidance to the llm about certain entities and relationships.

i believe the application should be able to do all CRUD operations. it may make sense to use some sort of versioning of files that the llm touches (via metadata?) so the user can easily identify what is llm activity and what is human activity. I havent looked into putting a vault into github, but perhaps that would work. this would also address the question of conflicts.

the solution needs to be multi modal.

i would love to have the interaction happen both in obsidian - there are many plugins that do some version of brining llm capabilities in. I woukd also want to be able to it outside of obsidian.. ideally as a "tool" in say OpenAI agents or in AutoGen. at the very least it should expose an api ala fastapi

finally one thing i use obsidian for is quickly capturing urls to things i find interesting.. ala Pocket. I want the system to take a url i "Share" to it and have memgpt call a web scraping tool that has good capabilities to deal with sites like linkedin and others that are not scraper friendly and have it do a summary (or full text extraction) of the content at that url/uri.

thanks so much Aashish

best,
nick



Sent from Surface Duo
________________________________

**Comment by nickknyc** [comment]
also consider this ***@***.***_38602/make-knowledge-graph-rag-with-llamaindex-from-own-obsidian-notes-b20a350fa354

as well as his lionagi/autogen/LlamaIndex post

Sent from Surface Duo
________________________________
