### ISSUE TITLE
Open AI error when calling Azure Open AI from autogen with MemGPT configuration

### ISSUE THREAD

**Issue by ompanda** [letta-ai/letta#660]
Getting below error while using Azure Open AI and all the Azure Open AI variables are configure.
_OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable_

**Comment by ferrygun** [comment]
I wrote a guide here which may help you https://djajafer.medium.com/analyse-the-workato-job-log-with-memgpt-and-autogen-334c93daf6d2

**Comment by cpacker** [comment]
Can you provide more details? eg from the github issue template?

**Describe the bug**
A clear and concise description of what the bug is.

**Please describe your setup**

- [ ] MemGPT version
  - What is the output of `memgpt version`? (eg "0.2.4")
- [ ] How did you install memgpt?
  - `pip install pymemgpt`? `pip install pymemgpt-nightly`? `git clone`?
- [ ] Describe your setup
  - What's your OS (Windows/MacOS/Linux)?
  - How are you running `memgpt`? (`cmd.exe`/Powershell/Anaconda Shell/Terminal)

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by ompanda** [comment]
i have installed latest pymemgpt  version in windows running from conda
