### ISSUE TITLE
Better prompt formatting selection in UI

### ISSUE THREAD

**Issue by jimlloyd** [letta-ai/letta#793]
**Is your feature request related to a problem? Please describe.**
Yes. The concept of "Wrappers" for selecting prompt format styles is confusing users and its difficult to determine which wrapper is appropriate for a given model.

See https://discord.com/channels/1161736243340640419/1162172996715290694/1193452126307889152
 
**Describe the solution you'd like**

1. Change `--model-wrapper` to `--prompt-formatter`.
2. Create a curated list of model prompt formats and use a good short name like `chatml` for each. This curated list should be very easily accessible, perhaps even embedded in the help usage.

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A

**Comment by cpacker** [comment]
This is good - we just need to be wary of backwards compatibility.

Because 0.2.12 will include a significant DB refactor, we might be able to move this change into 0.2.12. However we probably still want some form of backwards compatibility (maybe allowing `--model-wrapper` to be passed in as well as an alias?).
