### ISSUE TITLE
Allow tweaking parameters for ChatCompletion routes

### ISSUE THREAD

**Issue by cpacker** [letta-ai/letta#859]
**Is your feature request related to a problem? Please describe.**

Currently users can tweak parameters for LLM backends that use `Completion` APIs (eg llama.cpp, webui, etc) as shown in https://memgpt.readme.io/docs/local_llm_settings, but not for the LLM backends that use `ChatCompletion` APIs (eg OpenAI, OpenAI Azure).

**Describe the solution you'd like**

Add a parallel file to `~/.memgpt/settings/completions_api_settings.json`, called `~/.memgpt/settings/chat_completions_api_settings.json`, that gets read on OpenAI (+OpenAI proxy) and Azure OpenAI LLM calls.

**Comment by robbyt** [comment]
@cpacker handling various differences in LLM/Embeddings providers should be handled at a larger macro level, instead of per-parameter or with special handling for various API feature differences. 

Each LLM backend should have a profile with these various settings (such as API URL, auth, capabilities). There should be several pre-populated profiles, as well as the ability for a user to define their own profiles.

How could you make the LLM or Embedding implementation in the main application become a completely abstract provider? How could you make the LLM/Embedding backend modular?

**Comment by cpacker** [comment]
If you wanted to modularize this you could potentially make one completion route script, one chatcompletion route script, and have the POST and response handling done by parameterized functions. E.g. for webui, you have a different lambda function or parameterized "response_handler" than for lmstudio. This is effectively what's being done in the existing per-backend api.py scripts.

If you're interested in trying to modularize this better, definitely happy to review an initial proposal + PR! Atm I don't think it's the highest priority because most of the popular self-host LLM backends are covered, and closed / key only completion route APIs can now be handled via #835, but I do agree this would make the codebase much nicer so I think it's a valuable refactor.
