### ISSUE TITLE
Updating LanceDB integration for 0.3 refactor

### ISSUE THREAD

**Issue by PrashantDixit0** [letta-ai/letta#947]
@sarahwooders Please add the outline step to refactor the LanceDB code for the 0.3 version

**Comment by sarahwooders** [comment]
Hi @PrashantDixit0 could you please model the integration based on the [chroma](https://github.com/cpacker/MemGPT/blob/main/memgpt/agent_store/chroma.py) and[ postgres](https://github.com/cpacker/MemGPT/blob/main/memgpt/agent_store/db.py#L424) integrations?  

The main thing that's changed is that we now assume that all data (for a given table type) is contained within a single table, even if its coming from multiple users/agents. We implemented this by adding a `StoreConnector.filters` field which specifies the user/agent filters for that storage connection, so that data is filtered automatically when we query (e.g. if we run a vector query, we only want results corresponding to the user/agent). We also allow for additional filters in the query, so those need to be combined with the default filters (as done [here](https://github.com/cpacker/MemGPT/blob/main/memgpt/agent_store/chroma.py#L42) for chroma).

I think the main other todos other than implementing the storage connector are: 
* Update `cli/cli_config.py` to include LanceDB as an option for archival memory 
* Write tests in `test_load_archival.py` and `test_storage.py`

Please let me know if you have any other questions!
