### ISSUE TITLE
Allow returning >40 rows for indexed PostgreSQL Search 

### ISSUE THREAD

**Issue by sarahwooders** [letta-ai/letta#975]
**Is your feature request related to a problem? Please describe.**
If we add an index to PostgreSQL #974, we will be constrained to 40 results per query unless we explicitly set this field to be higher. 

**Describe the solution you'd like**
An initial prototype of the solution is to set the `hnsw.ef_search` field to be higher on a vector search, but we should find a more efficient way to do this (if there is): 
```
    def query(self, query: str, query_vec: List[float], top_k: int = 1000, filters: Optional[Dict] = {}) -> List[RecordType]:
        filters = self.get_filters(filters)
        with self.session_maker() as session:
            st = time.time()
            if top_k > 40:
                session.execute(text(f"SET hnsw.ef_search = {top_k};"))  
                session.commit()
            results = session.scalars(
                select(self.db_model).filter(*filters).order_by(self.db_model.embedding.cosine_distance(query_vec)).limit(top_k)
            ).all()
            et = time.time() 
            print(f"Query time: {et-st:.2f}s")

        # Convert the results into Passage objects
        records = [result.to_record() for result in results]
        return records
```

**Comment by jward92** [comment]
Hey there - I'm interested in taking a look at this for my first contribution!

**Comment by ClarifyJonathan** [comment]
@sarahwooders Right now the vector fields are set with a max dimension of 4096: https://github.com/cpacker/MemGPT/blob/4bfd0de422436493a1fb8f50aa1e8ecb8b4db182/memgpt/constants.py#L13

Postgres indexes on vector fields are currently limited at 2000 dimensions: https://github.com/pgvector/pgvector?tab=readme-ov-file#hnsw. Would you be ok limiting the embedding dimension to 2000 for postgres?

**Comment by jward92** [comment]
@sarahwooders Right now the vector fields are set with a max dimension of 4096: https://github.com/cpacker/MemGPT/blob/4bfd0de422436493a1fb8f50aa1e8ecb8b4db182/memgpt/constants.py#L13

Postgres indexes on vector fields are currently limited at 2000 dimensions: https://github.com/pgvector/pgvector?tab=readme-ov-file#hnsw. Would you be ok limiting the embedding dimension to 2000 for postgres?

**Comment by jward92** [comment]
@sarahwooders Linked a WIP that would enable indexes on postgres vector columns. It's a bit hacky as it would result in storing embeddings in different sizes depending on the database since postgres only supports indexes on vector columns up to 2000 dimensions. Took a look around and there are few potential alternate solutions I could see:

1. Limit all embeddings to 2000 for all databases. I think this would work in the short-term as I don't see any current support for embedding models that use > 2000 dimensions but would limit support for other embedding models. Would almost definitely break existing environments. 
2. Try using halfvec in postgres which supports indexes up to 4000 dimensions (still would be slightly different than the current 4096 limit)
3. Not sure how stable this is https://github.com/tensorchord/pgvecto.rs but looks like it supports indexes on vector cols > 4096 dimensions

**Comment by jward92** [comment]
Just found this issue: https://github.com/cpacker/MemGPT/issues/1028. If you're comfortable decreasing dimensions down to 1536, I can incorporate in this PR and then also update the db migration code.

**Comment by jward92** [comment]
@sarahwooders https://github.com/cpacker/MemGPT/pull/1603 FYI - ready for review. Thanks!
